Project focused on evaluating miR-21 / miR-34 expression ratio as predictor of lung-cancer-patient survival 

```{r}
#wczytywanie paczek 
library(TCGAbiolinks)
```

```{r}
#pobieranie konkretnych projektow

getGDCprojects()
TCGAbiolinks:::getProjectSummary("TCGA-LUAD")
TCGAbiolinks:::getProjectSummary("TCGA-LUSC")

query <- GDCquery(project = "TCGA-LUSC", legacy = FALSE, data.category = "Transcriptome Profiling", data.type = "miRNA Expression Quantification", sample.type = c("Primary solid Tumor", "Solid Tissue Normal"))

query2 <- GDCquery(project = "TCGA-LUAD", legacy = FALSE, data.category = "Transcriptome Profiling", data.type = "miRNA Expression Quantification", sample.type = c("Primary solid Tumor", "Solid Tissue Normal"))

GDCdownload(query, directory = "./data")
GDCdownload(query2, directory = "./data")

library(SummarizedExperiment)

scExp <- GDCprepare(query = query, save = TRUE, save.filename = "sc.rda", directory = "./data/")
adExp <- GDCprepare(query = query2, save = TRUE, save.filename = "ad.rda", directory = "./data/")
```

```{r}
#get  data from files
load(file = "ad.rda")
ad <- data

load(file = "sc.rda")
sc <- data

rownames(ad) <- ad[, 1]
rownames(sc) <- sc[, 1]

ad <- ad[c("hsa-mir-21", "hsa-mir-34a"), ]
sc <- sc[c("hsa-mir-21", "hsa-mir-34a"), ]

ad <- ad[, grep("million*", colnames(ad))]
sc <- sc[, grep("million*", colnames(sc))]

library(stringr)

helper <- colnames(ad)
helper <- str_extract(helper, regex("TCGA-.{23}"))

colnames(ad) <- helper
colnames(sc) <- str_extract(colnames(sc), regex("TCGA-.{23}"))

save(ad, sc, file = "datasets.rda")
```

